sudo: required
language: node_js
services:
  - docker

before_install:
  - docker pull ubuntu:16.04
  - docker build -t kore -f kore/Dockerfile kore/
  - docker build -t servo -f Dockerfile .
  - docker run -p 8080:8080 -t servo kodev run

script:
  - cd js
  - npm install -g grunt
  - npm install
  - grunt nodeunit