language: c
sudo: false
compiler:
  - clang
  - gcc

before_install:
  - wget www.endlessinsomnia.com/kore_2.1.dev1_amd64.deb
  - sudo dpkg -i kore_2.1.dev1_amd64.deb

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - libssl-dev
      - zlib-dev
      - python3.6-dev
script:
  - make