version: "3.0"

services:
  servo:
    build: .
    image: servo:latest
    command: servo --debug
    env_file: ./secrets.env
    volumes:
      - .:/src/servo
    working_dir: /src/servo
    ports:
      - 8080:8080
    expose:
      - 8080

  console:
    depends_on:
      - servo
    build: ./src/js
    image: servo-console:latest
    tty: true
    volumes:
      - ./src/js:/src/servo/js
      - /src/servo/js/node_modules
    working_dir: /src/servo/js
    command: node app/index.js
    ports:
      - 5000:5000

  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    expose:
      - 5432
    env_file: ./secrets.env
    volumes:
      - postgresql-db:/var/lib/postgresql

volumes:
  postgresql-db:
    driver: local
